datetime: '2025-07-27T09:59:59.138637+08:00'
source: (源链接)[booknatureoftech_files/book.html]
title: 📚《技术的本质》- 动态交互核心摘要
tags:
- technology
- history
- philosophy
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]