title: 《现实换向 Reality Transurfing》核心精粹摘要
datetime: '2025-06-16T14:12:22+0800'
tags:
  - transurfing
  - reality
  - mind
description: 现实换向核心思想精要
source: ()[]
attachments:
  - (《Reality Transurfing》)[realitytransurfing.pdf]
