title: 基于AI的规范驱动开发：新开源工具包入门指南
datetime: 2025-09-08T13:30:36.571955+08:00
tags:
- spec-driven
- ai-development
- programming
description: 介绍GitHub开源的Spec Kit工具包，通过规范驱动开发方法提高AI编程代理的效率和准确性，包含四个核心阶段：规范化、计划、任务化和实施。
source: (GitHub博客原文)[https://github.blog/ai-and-ml/developers-can-use-their-ai-tool-of-choice-for-spec-driven-development-with-this-open-source-toolkit/]
attachments:
links:
- (Spec Kit GitHub仓库)[https://github.com/github/spec-kit]
- (GitHub Copilot)[https://github.com/features/copilot]
- (Claude Code)[https://claude.ai/code]