datetime: '2025-07-29T09:56:43.782436+08:00'
source: (源链接)[book_AI_engineering_files/book.html]
title: 📚 《AI工程》核心摘要 (动态交互版)
tags:
 - ai
 - engineering
 - book
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]