datetime: '2025-09-06T08:35:53.328351+08:00'
source: (源链接)[book_simply_compexity_files/book.html]
title: 📚 《简单复杂性》核心摘要
tags:
- complexity
- book
- science
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]