title: 汪华最新预言：AI时代的核心是实现，而非连接
datetime: '2025-06-24T12:48:40.861736+08:00'
tags:
- ai
- investment
- startup
description: 汪华解读AI时代投资与创业新范式
source: (原文)[https://mp.weixin.qq.com/s/4dmZVqPln5rN239RvO8VkA]
