title: 让 AI 自己编写一个 PDF 翻译工具
datetime: 2025-06-07T10:00:00+0800
tags:
- ai
- pdf
- cursor
description: 使用 Cursor 让 AI 自己编写一个 PDF 翻译工具的完整过程，包括需求分析、代码编写、调试优化和翻译实战
source: {}
attachments: []
links:
- (原始书籍)[/ai/spoolprj.html]
- (生成效果)[/ai/spoolprjcn.html]
