title: 从手动到自动：用 Claude Code 构建博客发布工作流
datetime: '2025-09-09T20:46:44+08:00'
tags:
- automation
- claude
- workflow
description: 记录了如何将原本需要多个工具协作的博客发布流程，整合成一个 Claude Code 命令搞定的自动化方案，从手动切换三个工具到一条命令完成发布。
source: (原文链接)[/write/20250909_auto_blog_workflow.md]
attachments:
links:
- (Claude Code 文档)[https://docs.anthropic.com/en/docs/claude-code]