datetime: '2025-09-01T16:00:46.599530+08:00'
source: (源链接)[book_situational_awareness_files/book.html]
title: 📚 《未来十年形势感知》摘要
tags:
- agi
- intelligence
- future
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]