datetime: '2025-06-19T11:45:15.732827+08:00'
source: (小宇宙播客《边角聊》)[https://www.xiaoyuzhoufm.com/episode/684a1c3d574f065721b252ee?s=eyJ1IjogIjYyYzNjMzkwZWRjZTY3MTA0YTFhMGRhNSJ9]
title: 动态摘要：《"为你好"的代价：升学焦虑下的父母众生相》
tags:
- education
- anxiety  
- parenting
description: 升学摇号制度下父母焦虑与亲子关系探讨
