title: 与 DHH 一起「怦然心动」- 交互式摘要
datetime: '2025-06-30T18:49:55.891088+08:00'
tags:
- konmari
- programming
- business
description: DHH将整理哲学应用于编程和商业
source: (原文)[https://37signals.com/podcast/spark-joy-with-dhh/]
links:
- (怦然心动整理术)[konmari.html]