datetime: '2025-07-17T14:36:07.726742+08:00'
source: (源链接)[https://arxiv.org/abs/2507.11473]
title: 论文摘要：思想链（CoT）的可监控性
tags:
- ai
- cot
- security
description: 思想链（CoT）的可监控性
attachments:
- (论文)[2507.11473v1.pdf]
