datetime: '2025-09-16T20:54:51.617504+08:00'
source: (源链接)[book_a_drive_to_survive_files/book.html]
title: 📚 《生存驱动：自由能原理与生命意义》摘要
tags:
 - survival
 - life
 - mind
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]