datetime: '2025-07-29T09:57:24.020163+08:00'
source: (源链接)[book_statistical_for_ML_files/book.html]
title: 📚 《面向数据科学家的实用统计学》核心摘要
tags:
 - ai
 - ML
 - statistics
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]