datetime: '2025-08-26T18:21:48.488543+08:00'
source: (源链接)[how_people_use_ai_202504_files/book.html]
title: 《2025年人们如何真正使用生成式AI》- 深度交互摘要
tags:
 - genAI
 - agentic
 - sophistication
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]