datetime: '2025-08-11T18:50:51.654657+01:00'
source: (源链接)[book_countdown_to_preparedness_files/book.html]
title: 《倒计时准备》核心摘要
tags:
 - survival
 - prepare
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]