title: 将 Cursor 常用操作转化为 Claude Code 命令
datetime: '2025-09-09T20:43:27+08:00'
tags:
- cursor
- claude
- automation
description: 分享如何将 Cursor 上频繁重复的手动操作整理成标准化 prompt，转化为 Claude Code 的自定义命令，实现带 LLM 能力的全自动化工作流
source: (原文)[/write/20250909_cursor_to_claude_code.md]
attachments:
links: