datetime: '2025-08-06T08:54:35.240717+08:00'
source: (源链接)[book_consciousness_files/book.html]
title: 📚 《意识：一个浪漫还原论者的自白》
tags:
 - scince
 - consciousness
 - neuroscience
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]