title: AI对就业与社会影响：Dario Amodei访谈摘要
datetime: 2025-06-03 19:57:08+08:00
tags:
- ai
- employment
- interview
description: Anthropic CEO Dario Amodei关于AI技术对就业市场和社会结构深远影响的深度访谈摘要
source: ''
attachments: []
links: []
