attachments: []
datetime: '2025-06-05T12:58:24.795237+08:00'
description: Anthropic CEO Dario Amodei关于AI技术对就业市场和社会结构深远影响的深度访谈摘要
links: []
source: ''
tags:
- ai
- employment
- interview
title: AI对就业与社会影响：Dario Amodei访谈摘要
