title: 痛苦的教训
datetime: '2025-09-09T13:55:26+08:00'
tags:
- ai
- machinelearning
- research
description: Rich Sutton关于人工智能研究的重要观察：依靠计算能力和通用方法比依赖人类专业知识更有效，通过象棋、围棋、语音识别等实例说明了这一痛苦但重要的教训。
source: (The Bitter Lesson)[http://www.incompleteideas.net/IncIdeas/BitterLesson.html]
attachments:
links:
- (Rich Sutton个人网站)[http://www.incompleteideas.net/]