datetime: '2025-06-05T13:51:19.769923+08:00'
source: (Hacker News讨论)[https://news.ycombinator.com/item?id=44163063]
title: Hacker News 评论摘要
description: AI辅助编程观点对立
tags:
- ai
- programming
- debate
links:
- (我的AI怀疑论朋友们都疯了)[allnuts.html]
