title: 文章摘要：我的AI怀疑论朋友们都疯了
datetime: '2025-06-05T13:50:50.861362+08:00'
tags:
  - ai
  - programming
  - llm
description: 一篇关于AI辅助编程的观点文章
source: (原文)[https://fly.io/blog/youre-all-nuts/]
links:
  - (Hacker News网友评论)[allnutscomment.html]