datetime: '2025-06-16T15:46:05+0800'
title: 《2025团队状态报告》动态摘要 | Atlassian
tags:
  - report
  - team
  - AI
description: 团队信息管理与AI洞见
source: (原文)[https://www.atlassian.com/]
attachments:
  - (《the state of teams 2025》)[the-state-of-teams-2025.pdf]
