datetime: '2025-09-02T12:09:46.847107+08:00'
source: (源链接)[book_future_mind_files/book.html]
title: 📚 《心灵的未来》书籍摘要
tags:
 - book
 - mind
 - science
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]