datetime: '2025-08-26T19:06:47.910656+08:00'
source: (源链接)[book_timeboxing_files/book.html]
title: 📚 《时间盒法 (Timeboxing)》深度摘要
tags:
 - timeboxing
 - time management
 - productivity
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]
