datetime: '2025-08-23T16:37:30.994663+08:00'
source: (源链接)[https://www.youtube.com/watch?v=DAQJvGjlgVM&ab_channel=Anthropic]
title: 深度解析 Claude Code：与产品经理 Kat 的对谈精华
tags:
- claude
- product
- interview
