datetime: '2025-09-04T23:17:15.304299+08:00'
source: (源链接)[https://youtu.be/tLRCS48Ens4?si=pr7eNEE16ovFaP_T]
title: Huberman Lab 心理健康系列 (与 Paul Conti 博士) - 视频摘要
tags:
- psychology
- health
- huberman
