datetime: '2025-06-06T09:42:10.757250+08:00'
source: (原文)[https://www.bilibili.com/video/BV1TRTAzZEZw]
title: 情绪价值核心要点
tags:
 - emotion
 - value
 - psychology
description: 情绪价值的定义、应用与反思
attachments: []