title: 视频摘要：Andrew Ng 与 Harrison Chase 的炉边谈话
datetime: 2025-06-07T20:19:45+08:00
tags: 
 - ai
 - langChain
description: Andrew Ng 与 Harrison Chase 在 LangChain Interrupt 大会的炉边谈话摘要，涵盖智能体性概念、工作流构建、语音应用前景、AI辅助编程以及AI创业建议等核心主题。
source: (YouTube视频)[https://www.youtube.com/watch?v=4pYzYmSdSH4]
