attachments: []
datetime: '2025-06-05T12:58:24.908736+08:00'
description: 详细解析社交平台的内容传播机制，包括基础曝光逻辑、社交裂变效应、转发扩散和二度人脉加持等核心原理
links: []
source: ''
tags:
- social
- content
- algorithm
title: 社交平台内容传播机制详解
