datetime: '2025-06-24T12:49:24.622034+08:00'
source: (罗永浩访谈摘要：关于AI、创业与未来计划)[https://mp.weixin.qq.com/s/IA450hWP_fRSHVrr6I_EXg?scene=1]
title: 罗永浩访谈摘要：关于AI、创业与未来计划
tags:
- ai
- startup
- podcast
description: 罗永浩谈AI创业与播客计划
