datetime: '2025-08-25T18:14:41.676249+08:00'
source: (源链接)[book_ai_delivery_files/book.html]
title: 📚 《AI原生软件交付》核心摘要 (LLM应用突出版)
tags:
 - devops
 - ai-native
 - delivery
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]