title: 使用 LLM 辅助阅读时的体验感受
datetime: '2025-09-09T12:42:40+08:00'
tags:
- llm
- reading
- ai
description: 通过对比同一素材的两次摘要，探讨带着目标使用LLM阅读的重要性，强调兴趣、注意力和领域经验在AI辅助阅读中的关键作用
source: (原文)[/write/20250909_ai_summary.md]
attachments:
links:
- (Claude Code CEO访谈)[https://www.laobu.com/ai/claudecodeceo.html]
- (Boris Claude Code访谈)[https://www.laobu.com/ai/yt_talk_with_boris_claudecode.html]