datetime: '2025-08-27T10:22:53.487518+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1jTedzREds/?spm_id_from=333.1007.top_right_bar_window_history.content.click&vd_source=837ab5022a806ebb29ebc1b0a7afbf21]
title: 何小鹏 × 罗永浩 创业故事摘要
