title: 从神经网络起步到大型模型：模型与方法的发展历程
datetime: 2025-07-24T14:28:15+08:00
tags:
- neuralnetwork
- deeplearning
- ai
description: 系统梳理自早期神经网络应用以来的重要模型、方法和成功案例，包括神经网络架构发展、学习范式演进、大型语言模型路线、关键训练技巧，以及这些技术在实际任务中的里程碑式突破。从感知机到Transformer，从监督学习到自监督学习，从AlphaGo到ChatGPT，探索推动机器学习从早期走向现代的关键技术。
