datetime: '2025-09-03T13:24:27.486375+08:00'
source: (源链接)[book_agentic_design_patterns_files/book.html]
title: 📚 《智能体设计模式》核心摘要
tags:
 - agentic
 - design
 - pattern
attachments:
 - (中文Docx)[book.docx]
 - (中文epub)[book.epub]
links:
 - (作者原书)[https://docs.google.com/document/d/1rsaK53T3Lg5KoGwvf8ukOUvbELRtH-V0LnOIFDxBryE/preview?tab=t.0#heading=h.pxcur8v2qagu]