datetime: '2025-09-16T22:02:13.718477+08:00'
source: (源链接)[book_active_inference_files/book.html]
title: 📚 书籍摘要：主动推断 (Active Inference)
tags:
 - active
 - mind
 - predictive
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]