datetime: '2025-07-31T10:41:45.583385+08:00'
source: (中文翻译)[book_a_system_for_writing_files/book.html]
title: 📚 《一个写作的系统》书籍摘要
tags:
 - zettelkasten
 - writing
 - methodology
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]