title: 人格研究中的"能动"与"共生"及其关系 - 交互式摘要
datetime: 2025-06-07T20:48:26+0800
tags:
- psychology
- personality
- mind
description: 系统梳理人格研究中"能动"(Agency)与"共生"(Communion)两个核心概念，探讨它们在特质、动机、价值观等不同人格领域中的内涵及相互关系，分析关系分歧的原因和未来研究方向的学术综述。
attachments:
- (论文.pdf)[人格研究中的“能动”与“共生”及其关系.pdf]
