datetime: '2025-06-24T18:25:14.741593+08:00'
source: (对谈视频)[https://www.youtube.com/watch?v=mZUG0pr5hBo]
title: Sam Altman 与 Jack Altman 关于 AI 未来的对话摘要
tags:
- ai
- interview
- openai
description: Sam Altman 与兄弟 Jack 对话，探讨 AI 未来发展
