title: LangChain Interrupt 大会产品主题演讲摘要
datetime: 2025-06-07T20:21:12+0800
tags:
  - langchain
  - agents
description: Harrison Chase (LangChain CEO) 在 Interrupt 大会上的产品主题演讲摘要，涵盖LangChain的诞生缘起、核心挑战、使命愿景以及基于6个核心信念构建的产品哲学与发布策略
source: (视频)[https://www.youtube.com/watch?v=DrygcOI-kG8]
