title: AI新技能不是提示工程，而是上下文工程
datetime: '2025-06-30T16:00:00+08:00'
tags:
  - context
  - engineering
  - ai
description: 探讨AI开发中从提示工程向上下文工程的重要转变，深入分析如何为LLM提供正确的上下文以构建高效的AI代理系统
links:
  - (Tobi Lutke推文)[https://x.com/tobi/status/1935533422589399127]
  - (Karpathy推文)[https://x.com/karpathy/status/1937902205765607626]
  - (LangChain：上下文工程的兴起)[https://blog.langchain.com/the-rise-of-context-engineering/]
  - (拥有你的上下文窗口)[https://github.com/humanlayer/12-factor-agents/blob/main/content/factor-03-own-your-context-window.md]
  - (Simon Willison的上下文工程)[https://simonwillison.net/2025/Jun/27/context-engineering/]
  - (代理的上下文工程)[https://rlancemartin.github.io/2025/06/23/context_engineering/]