title: Augmented Coding：超越感觉驱动的编程方式
datetime: '2025-09-10T08:16:40+08:00'
tags:
- ai
- coding
- programming
description: 探索 Augmented Coding 与 Vibe Coding 的本质区别，通过 B+ Tree 项目实践，展示 AI 时代的编程工作流和编程未来的启示。
source: (原文 markdown)[/write/20250910_augmented_coding_beyond_vibes.md]
attachments:
links:
- (BPlusTree3 项目)[https://github.com/example/BPlusTree3]