datetime: '2025-08-21T02:56:42.733194+08:00'
source: (源链接)[book_ceodiary_files/book.html]
title: 📚 《CEO日记：商业与生活的33条法则》核心摘要
tags:
 - ceo
 - business
 - life
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]