datetime: '2025-09-08T15:07:44.795325+08:00'
source: (源链接)[https://www.youtube.com/watch?v=yoycgOMq1tI&ab_channel=SequoiaCapital]
title: 红杉资本：AI认知革命摘要
tags:
- investment
- artificial-intelligence
- venture-capital
