title: 优秀产品经理与糟糕产品经理的区别
datetime: '2025-09-14T09:13:22+08:00'
tags:
- product
- management
- strategy
description: 来自 Ben Horowitz 的经典产品管理对比文章，通过对比优秀与糟糕产品经理的不同表现，帮助产品经理审视自身并明确改进方向。涵盖知识基础、时间管理、沟通方式、文档预见等关键维度。
source: (Ben Horowitz 原文)[https://a16z.com/2012/06/15/good-product-managerbad-product-manager/]
attachments:
links: