title: IndexTTS2 大版本升级，10分钟实现情绪饱满的播客
datetime: '2025-09-16T16:00:10+08:00'
tags:
- tts
- ai
- podcast
description: 利用IndexTTS2和AI工具，在10分钟内搭建完整的情绪播客生成流程，包含代码获取、环境调试、脚本生成、情绪解析和语音合成等完整步骤。
source: (原文)[/write/20250916_indextts2_emotional_podcast.md]
attachments:
links:
- (IndexTTS2项目)[https://github.com/index-tts/index-tts]
