datetime: '2025-06-30T18:27:43.377226+08:00'
title: 《Getting Real》交互摘要
tags:
- startup
- lean
- agile
description: Basecamp的软件开发理念与实践
attachments:
 - (《Getting Real》)[getting-real.pdf]
links:
- (Basecamp官网)[https://basecamp.com]
- (Getting Real原文)[https://basecamp.com/gettingreal]