datetime: '2025-07-03T14:29:07.491572+08:00'
source: (原文)[https://www.washingtonpost.com/technology/2025/07/02/ai-note-takers-meetings-bots/]
title: AI"替身"开会：效率神器还是社交杀手？ - 交互式摘要
tags:
- ai
- meeting
- work
description: AI代替人类参会的利弊分析