datetime: '2025-06-08T10:03:25.118592+08:00'
title: 《驾驭日常混沌》- 产品经理版摘要
tags:
- complexity
- ai
description: 一本关于技术、复杂性，以及我们如何在充满可能性的新世界中茁壮成长的书。作者大卫·温伯格探讨了从简化世界到拥抱复杂性的根本转变，挑战传统假设，提出新世界的策略与工具。
attachments:
- (中文书名《混沌的世界》)[../everydaychaos_files/EverydayChaos.pdf]
links:
- (中学生阅读)[everydaychaos.html]
- (产品经理阅读)[everydaychaospm.html]
- (AI创业者阅读)[everydaychaosai.html]
