datetime: '2025-07-25T14:55:26.878162+08:00'
source: (源链接)[atlassian2025dev_files/CSD-15683 State of DevEx Report 2025-FINAL_7.9.pdf]
title: Atlassian《2025年开发者体验状况》报告摘要
tags:
- ai
- atlassian
- jira
description: Atlassian《2025年开发者体验状况》报告摘要
attachments:
- (报告)[CSD-15683 State of DevEx Report 2025-FINAL_7.9.pdf]
