datetime: '2025-08-26T23:16:32.819960+08:00'
source: (源链接)[book_stoic_challenge_files/book.html]
title: 📚 《斯多葛挑战》- 动态交互核心摘要（详细版）
tags:
 - stoic
 - philosophy
 - mind
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]