datetime: '2025-07-23T20:02:28.823704+08:00'
source: (源链接)[book_art_of_camping_files/book.html]
title: 《露营的艺术》动态交互摘要
tags:
- camping
- history
- book
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]