title: 皂质学(Smegmatalogia)：18世纪苏格兰制皂与漂白工艺
datetime: '2025-08-19T23:00:00+08:00'
tags:
- soap
- bleaching
- scotland
description: 詹姆斯·邓巴1738年撰写的制皂与漂白技术指南，详述18世纪苏格兰传统工艺方法
source: (原文)[/write/smegmatalogia.md]