datetime: 2025-06-11T18:20:00.895136+08:00
source: (原文)[https://oem.bmj.com/content/82/3/105.long]
title: 论文摘要：过度工作与大脑结构变化：一项初步研究
tags:
  - overwork
  - neuroscience
description: 一项针对110名医疗保健工作者的初步研究，通过神经影像学方法探讨过度工作对大脑结构的影响，发现过度工作者在与执行功能和情绪调节相关的脑区（如中额回、脑岛）表现出显著的体积变化，为理解长时间工作对认知和情绪健康的神经生物学影响提供了新证据。
attachments:
  - (论文)[paper.pdf]