datetime: '2025-08-27T15:58:27.945685+08:00'
source: (源链接)[book_vibecoding_fies/book.html]
title: 📚 《Vibe Coding》核心摘要：人机协作编程的未来
tags:
 - vibe coding
 - ai coding
 - ai programming
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]