datetime: '2025-09-07T10:18:08.849355+08:00'
source: (源链接)[paper_open_why_hallucinate_files/paper.html]
title: 📚 论文摘要：语言模型为何会产生幻觉
tags:
 - ai
 - llm
 - hallucinate
attachments:
- (中文PDF)[paper.pdf]
- (中文epub)[paper.epub]