datetime: '2025-06-24T15:32:42.827679+08:00'
source: (原文)[https://www.youtube.com/watch?v=qOYkpLdYIIU]
title: AI焦点摘要：Canva CTO Brendan Humphreys 访谈 (清爽版)
tags:
- ai
- canva
- interview
description: Canva CTO分享AI战略与工程文化