datetime: '2025-09-12T12:57:20.875481+08:00'
source: (源链接)[/ai/blog/book_parallel_distributed_processing.html]
title: 《并行分布式处理》核心思想摘要
tags:
- cognitive-science
- neural-networks
- computational-theory
