datetime: '2025-06-19T17:26:29.468522+08:00'
source: (Youtube视频)[https://www.youtube.com/watch?v=LCEmiRjPEtQ]
title: 'Andrej Karpathy: AI时代的软件 - 交互式摘要'
description: 'Karpathy对AI时代软件的思考'
tags:
  - ai
  - software
  - karpathy
