datetime: '2025-06-18T13:47:18.113423+08:00'
source: (公众号原文)[https://mp.weixin.qq.com/s/mEIQegWcGjT20LuBehZ71g]
title: 言创万物创始人对话摘要：AI Coding vs AI SWE
tags: 
 - ai
 - se
 - agent
 - coding
description: AI重构软件工程的机会与挑战
