datetime: '2025-07-01T15:19:21.600204+08:00'
source: (原文)[https://www.philschmid.de/context-engineering]
title: AI新技能摘要：情境工程
tags:
- ai
- context
- engineering
description: 从提示工程到情境工程的AI发展趋势
attachments:
- (情境工程示意图)[context.png]
