datetime: '2025-08-27T18:08:52.488710+08:00'
source: (源链接)[book_genai_dev_files/book.html]
title: 📚 《软件开发的生成式AI》核心摘要
tags:
 - genai
 - develepment
 - aise
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]