title: 调用Claude翻译一整本电子书
datetime: 2024-07-22 10:00:00+08:00
tags:
- claude
- ai
- translate
description: 一篇关于使用Claude Code进行Vibe Coding，将英文电子书自动化翻译为高质量中文版本的实践分享，涵盖了从需求定义、LLM优化、代码生成到调试的全过程。
source: 
attachments:
links:
- (原始文章)[https://www.laobu.net/ai/primabowmaking/book.html] 