title: 调用Claude翻译一整本电子书
datetime: 2025-07-10T10:00:00+0800
tags:
 - claude
 - ai
 - vibe coding
description: 一篇关于使用Claude Code进行Vibe Coding，将英文电子书自动化翻译为高质量中文版本的实践分享，涵盖了从需求定义、LLM优化、代码生成到调试的全过程。
links:
 - (中文翻译电子书)[../primabowmaking_files/book.html] 
