datetime: 2025-06-07T13:14:53+0800
source: (Spoon Carving Project)[spoolprj.html]
title: 勺子雕刻项目书 - 中文翻译
attachments:
- (Spoon Carving Project Book.pdf)[../spoolprj_files/SpoonCarvingProjectBook.pdf]
tags:
- greenwoodcraft
- carving
- bushcraft
