attachments: []
datetime: '2025-06-05T12:58:24.901470+08:00'
description: Nvidia CEO黄仁勋与Michael Milken深度对话，探讨AI革命、技术出口限制、人才招聘等核心话题的视频摘要
links: []
source: ''
tags:
- nvidia
- ai
- interview
title: 视频摘要：Nvidia CEO 黄仁勋与 Michael Milken 对话
