title: 视频摘要：Nvidia CEO 黄仁勋与 Michael Milken 对话
datetime: 2025-06-01 14:30:00+08:00
tags:
- nvidia
- ai
- interview
description: Nvidia CEO黄仁勋与Michael Milken深度对话，探讨AI革命、技术出口限制、人才招聘等核心话题的视频摘要
source: ''
attachments: []
links: []
