datetime: '2025-08-22T01:51:18.601133+08:00'
source: (源链接)[book_wayfinders_files/book.html]
title: 📚 《寻路者》深度摘要 | Wade Davis
tags:
 - ethnosphere
 - anthropology
 - culture
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]