title: 2025年夏，与大语言模型编程（更新版）
datetime: 2025-07-21 15:30:25+08:00
tags:
  - llm
  - coding
description: 本文作者antirez结合自身经验，深入探讨了如何高效利用大语言模型（LLM）辅助编程，涵盖协作方式、模型选择、实际案例及其局限性，强调人类与LLM协作的重要性。
source: (原文)[https://antirez.com/news/154]
attachments: []
links:
  - (2025夏天)[https://antirez.com/news/154]
  - (2024春天)[https://antirez.com/news/140]