attachments: []
datetime: '2025-06-05T12:58:24.904696+08:00'
description: Survival International 2023年度报告摘要，关注全球原住民部落权利保护、土地守护及反殖民化自然保护运动的重要进展
links: []
source: ''
tags:
- indigenous
- rights
- report
title: Survival International 2023 年度报告摘要
