datetime: '2025-07-29T18:09:41.415657+08:00'
source: (源链接)[book_mindfxck_files/book.html]
title: 📚 《Mindf*ck》核心摘要 | 克里斯托弗·威利
tags:
 - facebook
 - ca
 - book
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]