datetime: '2025-06-30T14:04:16.851443+08:00'
source: (I deleted my second brain)[https://www.joanwestenberg.com/p/i-deleted-my-second-brain]
title: 摘要：我删除了我的"第二大脑"
tags:
- productivity
- knowledge
- minimalism
description: 放弃数字囤积重获思维自由的反思
links:
- (Obsidian官网)[https://obsidian.md/]
- (巴别图书馆)[https://en.wikipedia.org/wiki/The_Library_of_Babel]
