title: 尼泊尔2025年9月动乱：全面分析
datetime: '2025-09-11T15:30:54+08:00'
tags:
- nepal
- protest
- politics
description: 对2025年9月尼泊尔Z世代抗议运动的详细分析，从社交媒体禁令引发的动乱到政府垮台的全过程，探讨了根本原因、时间线、地理分布和长远影响。
source: (ChatGPT-5分析报告)[原英文文档]
attachments:
links:
- (尼泊尔政治动态)[https://www.reuters.com/world/asia-pacific/nepal/]