datetime: '2025-08-29T21:39:42.161049+08:00'
source: (源链接)[book_gunpower_tech_15c_files/book.html]
title: 📚 书籍摘要：《十五世纪的火药技术》
tags:
 - book
 - history
 - gunpowder
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]