datetime: '2025-06-05T14:33:56.691720+08:00'
source: (JD Vance Bitcoin 2025 演讲视频)[https://www.youtube.com/watch?v=hMK2ULrVq6A]
title: JD Vance 在 Bitcoin 2025 演讲摘要
tags:
- bitcoin
- politics
- cryptocurrency
description: JD Vance副总统在Bitcoin 2025大会演讲核心内容
