attachments: []
datetime: '2025-06-04T17:27:00+08:00'
description: Karpathy分享ChatGPT模型选择策略，Eric Hayes揭秘ChatGPT复杂记忆系统原理
links: []
source: ''
tags:
- ai
- chatgpt
- models
title: ChatGPT核心能力揭秘：模型选择与记忆系统
