datetime: '2025-09-11T13:15:50.727344+08:00'
source: (源链接)[book_bayesian_cognition_mind_files/book.html]
title: 书籍摘要：《贝叶斯认知模型：逆向工程心智》
tags:
- bayesian
- cognitive-science
- machine-learning
links:
 - (中文epub)[book.epub]