datetime: '2025-09-17T11:34:11.412134+08:00'
source: (源链接)[paper_openai_use_chatgpt_2025_files/book.html]
title: 《人们如何使用ChatGPT》论文摘要
tags:
 - ai
 - chatgpt
 - openai
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]