datetime: '2025-07-17T08:57:37.996692+08:00'
source: (源链接)[japanhandbook2025_files/book.html]
tags:
- japan
- defense
- whitepaper
title: 📚日本2025年《防卫白皮书》精华详览
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]