datetime: '2025-09-16T22:02:40.939982+08:00'
source: (源链接)[book_surfing_uncertainty_files/book.html]
title: 📚 《不确定性的冲浪者》一书摘要
tags:
 - mind
 - uncertainty
 - cognition
attachments:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]