datetime: '2025-09-11T13:11:39.204070+08:00'
source: (源链接)[paper_google_ai_empirical_software_writing_files/book.html]
title: 论文摘要：一个助力科学家编写专家级实证软件的AI系统
tags:
- research
- ai
- software
links:
 - (中文PDF)[book.pdf]
 - (中文epub)[book.epub]