datetime: '2025-07-23T15:44:39.789649+08:00'
source: (源链接)[replacingguilt_files/book.html]
title: 📚《破除内疚，重塑驱动力》- 交互式摘要
tags:
- motivation
- psychology
- self-improvement
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]