title: Atlassian Q3 FY25 财报摘要
datetime: '2025-06-05T16:14:09.659825+08:00'
tags:
 - atlassian
 - ai
 - rovo
description: AI驱动平台转型的强劲财务表现
source: (Atlassian Q3 FY25 财报)[https://s28.q4cdn.com/541786762/files/doc_financials/2025/q3/TEAM-Q3-2025-Shareholder-Letter.pdf]
attachments:
- (Atlassian Q3 FY25 财报)[TEAM-Q3-2025-Shareholder-Letter.pdf]
links:
  - (Atlassian Investor Relations)[https://investors.atlassian.com/]