datetime: '2025-08-30T15:56:00.508377+08:00'
source: (源链接)[https://www.youtube.com/watch?v=GfH4QL4VqJ0]
title: Python 简史：一部代码与社区的传奇
links:
 - (Python 简史)[https://www.bilibili.com/video/BV16WhizhE4A]
tags:
- python
- history
- programming
