datetime: '2025-09-18T11:57:13.510070+08:00'
source: (源链接)[paper_deepseek_r1_files/paper.html]
title: DeepSeek-R1 论文与同行评议交互式摘要
tags:
- deepseek
- ai
- paper
links:
 - (中文论文PDF)[paper_deepseek_r1_files/paper_cn.pdf]
 - (英文论文PDF)[paper_deepseek_r1_files/paper_en.pdf]
 - (同行评议中文翻译)[paper_deepseek_r1_files/peerreview.html]
 - (同行评议中文翻译PDF)[paper_deepseek_r1_files/peerreview_cn.pdf]
 - (同行评议英文翻译PDF)[paper_deepseek_r1_files/peerreview_en.pdf]