title: 为 AI 编写文档：最佳实践
datetime: 2025-06-19T19:00:00+0800
tags:
- ai
- documentation
- rag
description: "检索增强生成 (RAG) 系统如 Kapa 依赖您的文档来提供准确、有用的信息。本指南提供了创建既能有效服务于人类读者又能有效用于 RAG 系统中 AI/LLM 消费的文档的最佳实践。"
source: (Writing documentation for AI best practices)[https://docs.kapa.ai/improving/writing-best-practices]