datetime: 2025-06-10T15:30:00+0800
title: 书籍摘要：《河童》
tags:
- japanese-literature
- satire
description: 芥川龙之介代表作《河童》与《蜘蛛之丝》的详细摘要，包含施蛰存先生的中文译本分析。《河童》通过主人公误入河童世界的奇幻经历，深刻讽刺20世纪初期日本社会的种种弊病，涵盖资本主义批判、人性探索、艺术商品化等主题。《蜘蛛之丝》则是经典佛教寓言，阐述慈悲心与利他精神的重要性。
attachments:
- (河童日文书)[kappa.pdf]
links:
- (《日本阿尔卑斯的登山与探险》)[mountainjp.html]
