title: 并行分布式处理：认知微结构探索（第二卷）
datetime: '2025-09-12T13:03:15+0800'
tags:
- cognitive-science
- neural-networks  
- connectionism
- pdp-models
- distributed-processing
description: 认知科学经典巨著《并行分布式处理》第二卷完整中文翻译，深入探讨心理学过程和生物学机制的PDP模型。包含图式理论、TRACE语音模型、句子处理机制等开创性理论，为现代深度学习和人工神经网络奠定了理论基础。
source: (《并行分布式处理》第二卷原文全文)[file:///Users/bruce/git/xiaobu/write/book_parallel_distributed_processing.md]
attachments:
links:
- (MIT Press - PDP系列丛书)[https://mitpress.mit.edu/]
- (认知科学研究所 - UCSD)[https://cogsci.ucsd.edu/]