datetime: '2025-07-24T13:12:21.434140+08:00'
source: (源链接)[bookweprogramers_files/book.html]
title: 📚 《我们，程序员》动态交互摘要
tags:
- programming
- history
- ai
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]