title: Sönke Ahrens：AI时代的外部思维与卡片盒笔记法
datetime: '2025-08-07T15:20:00+08:00'
tags:
 - zettelkasten
 - ai
 - notetaking
description: 基于MindHack播客对《How to Take Smart Notes》作者Sönke Ahrens的访谈，结合三大AI模型归纳整理的外部思维与卡片盒笔记法指南。探讨在AI时代如何通过Zettelkasten系统构建复杂认知、培养批判性思维，以及如何利用Obsidian等现代工具实现思想的外化与深度连接。
source: (MindHack播客访谈)[https://www.laobu.net/ai/howtotakesmartnotes_ai_talk.html]
links:
 - (播客视频中文版)[https://www.bilibili.com/video/BV1XJh5z9EWh/]
 - (《How to Take Smart Notes》)[https://takesmartnotes.com]
 - (Obsidian官方社区)[https://obsidian.md/community]
