datetime: '2025-06-24T16:13:21.985628+08:00'
source: (Lovable)[https://lovable.dev/]
title: 20VC 访谈摘要：Lovable 创始人 Anton Osika
tags:
- ai
- startup
- interview
description: Lovable CEO访谈，分享AI创业经验与产品哲学
