title: 《日本阿尔卑斯的登山与探险》摘要
datetime: 2025-06-10T08:59:44+0630
tags: 
 - mountaineering
 - japan
 - history
description: 沃尔特·韦斯顿1896年著作的摘要，记录了作者四年间在日本中部高山地区（日本阿尔卑斯）的登山探险经历，包括地理探索、文化观察、自然风光描述和登山活动详细记录。
attachments:
  - (《日本阿尔卑斯的登山与探险》)[mountainjp.pdf]



